### PR TITLE
[ADD]Views folder

### PR DESCRIPTION
**Pull request by Hector-Camacho**

### CODE REVIEW

**Comment by ougc27** [comment]
Approved

**Comment by alan196** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/Jarsa/vehicle-maintenance-system/pull-request/3/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Jarsa/vehicle-maintenance-system) [Approved with PullApprove](https://pullapprove.com/Jarsa/vehicle-maintenance-system/pull-request/3/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Jarsa/vehicle-maintenance-system)

**Comment by ougc27** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/Jarsa/vehicle-maintenance-system/pull-request/3/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Jarsa/vehicle-maintenance-system)

**Comment by Hector-Camacho** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/Jarsa/vehicle-maintenance-system/pull-request/3/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Jarsa/vehicle-maintenance-system)

**Pull request merged**
